# Generated by Django 3.0.2 on 2020-02-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestep',
            name='id',
        ),
        migrations.AlterField(
            model_name='timestep',
            name='time_step',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
