# Generated by Django 3.0.3 on 2020-03-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerHostNames',
            fields=[
                ('hostname', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='FileModel',
        ),
        migrations.AddField(
            model_name='fmumodel',
            name='container_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmumodel',
            name='epw_file',
            field=models.FileField(default='', null=True, upload_to='./Media/'),
        ),
        migrations.AlterField(
            model_name='fmumodel',
            name='idf_file',
            field=models.FileField(default='', null=True, upload_to='./Media/'),
        ),
    ]
