# Generated by Django 3.0.3 on 2020-03-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='time_step',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='output',
            name='time_step',
            field=models.BigIntegerField(default=0),
        ),
    ]
