# Generated by Django 3.0.2 on 2020-01-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_timestep_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestep',
            old_name='user_id',
            new_name='user',
        ),
    ]
