# Generated by Django 3.0.2 on 2020-01-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20200131_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='timestep',
            new_name='time_step',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='timestep',
            new_name='time_step',
        ),
    ]
